// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

import (
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializedService(isError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializedDatabaseRepository() *DatabaseRepository {
	databasePostgres := NewDatabasePostgresql()
	databaseMysql := NewDatabaseMysql()
	databaseRepository := NewDatabaseRepository(databasePostgres, databaseMysql)
	return databaseRepository
}

func InitializedFooBarService() *FooBarService {
	fooRepository := NewFooRepository()
	fooService := NewFooService(fooRepository)
	barRepository := NewBarRepository()
	barService := NewBarService(barRepository)
	fooBarService := NweFooBarService(fooService, barService)
	return fooBarService
}

// injector.go:

var fooset = wire.NewSet(NewFooRepository, NewFooService)

var barset = wire.NewSet(NewBarRepository, NewBarService)
