version: "3.8"
services:
  app:
    build: .
    container_name: go-app-service
    # Memuat environment variables dari file .env di root proyek
    env_file:
      - .env
    # expose port 3000 to the outside world
    ports:
      - "3001:3000"
    depends_on:
      db:
        # check health status of db
        condition: service_healthy
    # restart the container if it crashes
    restart: unless-stopped

  # provide a named volume for persisting data
  db:
    image: mysql:8.0
    container_name: mysql-db-service
    env_file:
      - .env
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306" # expose port 3306 to the outside world
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db-data:
