services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - ENV=development
    depends_on:
      - db
      - migrate

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306" # Pastikan port sesuai dengan semua service
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: go_rest_api
    volumes:
      - db-data:/var/lib/mysql

  migrate:
    image: migrate/migrate
    volumes:
      - .:/db/migrations
    command: ["-database", "mysql://root:secret@tcp(db:3306)/go_rest_api?charset=utf8mb4&parseTime=True&loc=Local", "-path", "/migrations", "up"]
    depends_on:
      - db

volumes:
  db-data:
